project:
  type: website
  output-dir: docs

website:
  title: "The effects of parental care on inbreeding avoidance"
  navbar:
    left:
      - href: workbook.qmd
        text: Workbook

    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/tomkeaney/sexual_conflict_phenology_and_polyandry

format:
  html:
      theme: Lumen # browse these here: https://quarto.org/docs/output-formats/html-themes.html
      max-width: 1800px # adjust if your plots don't fit or you want more or less whitespace
      toc: true # do you want a table of contents, by default it floats as you scroll
      toc-location: left # where should it be displayed
      toc-title: "Sections"
      code-fold: true # fold code up for neater display
      smooth-scroll: true
      #lightbox: true # if you click on figures, they expand
      embed-resources: true # output doc contains all info needed to display html
      #fig-format: pdf
